########## Dataset configuration ##########
[dataset]
type = "spider2-lite"
split = "sqlite"
root_path = "data/spider2-lite"
save_path = "workspace/dataset/spider2-lite/sqlite.pkl"

########## Vector database configuration ##########
[vector_database]
embedding_model_name_or_path = "/hpc2hdd/home/bli303/hf_models/Qwen3-Embedding-0.6B"
use_qwen3_embedding = true
local_files_only = true
normalize_embeddings = false
store_root_path = "workspace/vector_database/spider2-lite/sqlite"
max_value_length = 100
lower_meta_data = true

########## Value retrieval configuration ##########
[value_retrieval]
n_results = 5
n_parallel = 12
save_path = "workspace/value_retrieval/spider2-lite/sqlite.pkl"
enable = false

[value_retrieval.llm]
model = "gemini-3-pro-preview-thinking"
base_url = "https://www.dmxapi.com/v1"
api_key = "sk-Qmcfb6qShuPwvX2knt4CqoN9JcB8dv7VbYZm6fFCl8kgBHaO"
max_tokens = 16384
temperature = 1.0
api_type = "openai"
fix_end_token = true

########## Schema linking configuration ##########
[schema_linking]
n_parallel = 16
save_path = "workspace/schema_linking/spider2-lite/sqlite.pkl"
direct_linking_sampling_budget = 2
reversed_linking_sampling_budget = 2
value_distance_threshold = 0.02

[schema_linking.llm]
model = "gemini-3-pro-preview-thinking"
base_url = "https://www.dmxapi.com/v1"
api_key = "sk-Qmcfb6qShuPwvX2knt4CqoN9JcB8dv7VbYZm6fFCl8kgBHaO"
max_tokens = 16384
temperature = 1.0
api_type = "openai"
fix_end_token = true

########## SQL generation configuration ##########
[sql_generation]
n_parallel = 16
save_path = "workspace/sql_generation/spider2-lite/sqlite.pkl"
dc_sampling_budget = 2
skeleton_sampling_budget = 2
icl_sampling_budget = 0

[sql_generation.llm]
model = "gemini-3-pro-preview-thinking"
base_url = "https://www.dmxapi.com/v1"
api_key = "sk-Qmcfb6qShuPwvX2knt4CqoN9JcB8dv7VbYZm6fFCl8kgBHaO"
max_tokens = 16384
temperature = 1.0
api_type = "openai"
fix_end_token = true

########## SQL revision configuration ##########
[sql_revision]
n_parallel = 16
save_path = "workspace/sql_revision/spider2-lite/sqlite.pkl"
checker_sampling_budget = 1

[sql_revision.llm]
model = "gemini-3-pro-preview-thinking"
base_url = "https://www.dmxapi.com/v1"
api_key = "sk-Qmcfb6qShuPwvX2knt4CqoN9JcB8dv7VbYZm6fFCl8kgBHaO"
max_tokens = 16384
temperature = 1.0
api_type = "openai"
fix_end_token = true

########## SQL selection configuration ##########
[sql_selection]
n_parallel = 16
save_path = "workspace/sql_selection/spider2-lite/sqlite.pkl"
filter_top_k_sql = 2
evaluator_sampling_budget = 3
shortcut_consistency_score_threshold = 0.6

[sql_selection.llm]
model = "gemini-3-pro-preview-thinking"
base_url = "https://www.dmxapi.com/v1"
api_key = "sk-Qmcfb6qShuPwvX2knt4CqoN9JcB8dv7VbYZm6fFCl8kgBHaO"
max_tokens = 16384
temperature = 1.0
api_type = "openai"
fix_end_token = true